project:
  type: website

website:
  title: "CSC 132"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Lessons
        menu: 
          - text: 01 More on Data Structures
            href: lessons/01 More on Data Structures/index.qmd
          - text: 02 More on Data Structures
            href: lessons/02 More on Objects/index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



